#!/usr/bin/env python3
"""
add_font.py — Convert a single TTF/OTF font to an epdiy C header and register it.

Usage:
    python add_font.py <font_file> <FontName> <size> [--compress]

Arguments:
    font_file   Path to a .ttf or .otf file.
    FontName    C-identifier name for the font family (e.g. "Roboto").
    size        Point size as an integer (e.g. 18).

Options:
    --compress  Compress glyph bitmaps with zlib (recommended, saves flash).

The generated header is placed at:
    module/userfonts/<FontName>/<fontname_lower>_<size>.h

The registry module/userfonts/userfonts.h is regenerated afterwards so the
font is available at the next firmware build.

Example:
    python add_font.py ~/Downloads/Roboto-Regular.ttf Roboto 18 --compress
"""

import argparse
import os
import re
import subprocess
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
FONTCONVERT = os.path.join(SCRIPT_DIR, "epdiy", "scripts", "fontconvert.py")
USERFONTS_DIR = os.path.join(SCRIPT_DIR, "module", "userfonts")
REGISTRY_PATH = os.path.join(USERFONTS_DIR, "userfonts.h")


def _valid_c_identifier(name: str) -> bool:
    return bool(re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name))


def _var_name(font_name: str, size: int) -> str:
    """Return the C variable name produced by fontconvert, e.g. 'Roboto_18'."""
    return f"{font_name}_{size}"


def convert_font(font_file: str, font_name: str, size: int, compress: bool) -> str:
    """
    Run fontconvert.py and return the path of the written header file.
    Raises SystemExit on failure.
    """
    if not os.path.isfile(font_file):
        sys.exit(f"Error: font file not found: {font_file}")
    if not _valid_c_identifier(font_name):
        sys.exit(f"Error: '{font_name}' is not a valid C identifier.")
    if size <= 0:
        sys.exit(f"Error: size must be a positive integer, got {size}.")
    if not os.path.isfile(FONTCONVERT):
        sys.exit(f"Error: fontconvert.py not found at {FONTCONVERT}")

    var_name = _var_name(font_name, size)
    out_dir = os.path.join(USERFONTS_DIR, font_name)
    os.makedirs(out_dir, exist_ok=True)

    header_filename = f"{font_name.lower()}_{size}.h"
    header_path = os.path.join(out_dir, header_filename)

    cmd = [sys.executable, FONTCONVERT, var_name, str(size), font_file]
    if compress:
        cmd.append("--compress")

    print(f"Converting {os.path.basename(font_file)} → {font_name} @ {size}pt …", flush=True)
    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode != 0:
        print(result.stderr, file=sys.stderr)
        sys.exit(f"Error: fontconvert.py failed (exit {result.returncode})")

    with open(header_path, "w", encoding="utf-8") as fh:
        fh.write(result.stdout)

    print(f"  Written: {os.path.relpath(header_path, SCRIPT_DIR)}", flush=True)
    if result.stderr.strip():
        # fontconvert prints diagnostics to stderr; pass them through
        print(result.stderr.rstrip(), file=sys.stderr)

    return header_path


def regenerate_registry():
    """
    Scan module/userfonts/*/<name>_<size>.h and rebuild userfonts.h.
    """
    entries = []  # list of (font_name, size, rel_include_path)

    if not os.path.isdir(USERFONTS_DIR):
        return  # nothing to do

    for family_dir in sorted(os.listdir(USERFONTS_DIR)):
        family_path = os.path.join(USERFONTS_DIR, family_dir)
        if not os.path.isdir(family_path):
            continue
        for filename in sorted(os.listdir(family_path)):
            if not filename.endswith(".h"):
                continue
            # Expect pattern: <name_lower>_<size>.h
            m = re.fullmatch(r"(.+)_(\d+)\.h", filename)
            if not m:
                continue
            size = int(m.group(2))
            include_path = f"{family_dir}/{filename}"
            var_name = _var_name(family_dir, size)
            entries.append((family_dir, size, include_path, var_name))

    lines = [
        "#pragma once",
        "// Auto-generated by add_font.py / convert_fonts.py — do not edit manually.",
        "// Re-run the script after adding or removing fonts.",
        "",
    ]
    for _, _, inc, _ in entries:
        lines.append(f'#include "{inc}"')
    lines.append("")
    lines.append("static const FontEntry user_font_table[] = {")
    for font_name, size, _, var in entries:
        lines.append(f'    {{"{font_name}", {size}, &{var}}},')
    lines.append("    {NULL, 0, NULL},  // sentinel")
    lines.append("};")
    lines.append("")

    os.makedirs(USERFONTS_DIR, exist_ok=True)
    with open(REGISTRY_PATH, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))

    rel = os.path.relpath(REGISTRY_PATH, SCRIPT_DIR)
    print(f"Registry updated: {rel} ({len(entries)} font(s))", flush=True)


def main():
    parser = argparse.ArgumentParser(
        description="Convert a TTF/OTF font to an epdiy C header and register it.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("font_file", help="Path to .ttf or .otf font file.")
    parser.add_argument("font_name", help="C-identifier font family name (e.g. Roboto).")
    parser.add_argument("size", type=int, help="Point size (e.g. 18).")
    parser.add_argument("--compress", action="store_true", help="Compress glyph bitmaps.")
    args = parser.parse_args()

    convert_font(args.font_file, args.font_name, args.size, args.compress)
    regenerate_registry()


if __name__ == "__main__":
    main()
